# Last edited on 2017-10-03 20:44:03 by jstolfi

PROG = nmeeg_cleanup

JS_LIBS := \
  libneuro.a \
  libgeo.a \
  libjs.a
  
IGNORE := \
  temp.c
  
OTHER_LIBS :=

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
