# Last edited on 2023-12-08 05:29:26 by stolfi

PROG = nmsim_mu0_diagram

JS_LIBS := \
  libneuro.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libfftw3.so

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
