# Last edited on 2021-08-23 13:07:22 by stolfi

PROG = nmeeg_animate

JS_LIBS := \
  libneuro.a \
  libimg.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libjpeg.so \
  /usr/lib/x86_64-linux-gnu/libpng.a \
  /usr/lib/x86_64-linux-gnu/libz.so

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
