# Last edited on 2020-12-24 18:27:16 by jstolfi

PROG := nmsim_elem_net_create_test

JS_LIBS := \
  libnmsim_e.a \
  libnmsim.a \
  libjs.a
  
OTHER_C_FLAGS := -pg

OTHER_LD_FLAGS := -pg

OTHER_LIBS :=

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make

