# Last edited on 2017-09-21 17:14:14 by jstolfi

PROG = nmeeg_make_imgbasis

JS_LIBS := \
  libneuro.a \
  liblsq.a \
  libimg.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS :=

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
