# Last edited on 2021-08-23 00:45:57 by stolfi

PROG = nmeeg_split_e128_gh2013

JS_LIBS := \
  libneuro.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS :=

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
