# Last edited on 2023-10-22 19:29:47 by stolfi

PROG = nmeeg_activity_plot

JS_LIBS := \
  libneuro.a \
  libppv.a \
  libimg.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS :=

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
