# Last edited on 2017-07-24 22:00:29 by stolfilocal

PROG := nmsim_test_020_pop
 
TEST_LIB := libnmsim.a

TEST_LIB_DIR := ../..

JS_LIBS := \
  libjs.a

include ${STOLFIHOME}/programs/c/GENERIC-LIB-TEST.make
 
all: do-test

do-test: ${PROG}
	${PROG}
