# Last edited on 2017-09-19 15:54:29 by jstolfi

PROG = nmeeg_filter

JS_LIBS := \
  libneuro.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libfftw3.so \

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
