# Last edited on 2017-09-19 16:08:08 by jstolfi

PROG = nmeeg_spectrum

JS_LIBS := \
  libneuro.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS := \
  /usr/lib/x86_64-linux-gnu/libfftw3.so

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
