# Last edited on 2023-10-27 22:07:12 by stolfi

PROG = nmeeg_split_e128_fn2023

JS_LIBS := \
  libneuro.a \
  libgeo.a \
  libjs.a
  
OTHER_LIBS :=

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
