# Last edited on 2023-10-22 11:23:04 by stolfi

PROG = nmeeg_plot_electrodes

JS_LIBS := \
  libneuro.a \
  libgeo.a \
  libeps.a \
  libjs.a \
  

include ${STOLFIHOME}/programs/c/GENERIC-PROGS.make
